== Data
=== Sources

==== FFXIVCensus
Data from https://ffxivcensus.com was used for the following raw .csv:

- Tribal_Interactions.csv -> https://ffxivcensus.com/#tribal

=== Transformations
==== Dim_isEndgame
- 'Dim_isEngame' is a boolean value

==== Dim_GrandCompany
- 'Dim_GrandCompany' is consists out of 3 Grand Companies and the lack of one.

==== Dim_Tribes
- 'Category' is renamed to 'Dim_Tribes'.
- 'Tribe' is renamed to 'V_Interactions'.

==== Sub_Tribe_Categories
- 'Dim_Tribes' is copied from Dim_Tribes.
- Every Dim_Tribe gets a Furry category assigned, which was evaluated by professional furries. Said category is saved in 'V_Category'.


=== Temporary Stuff!!!!

WARNING: This is temporary!

https://ffxivcensus.com/#commendations

TRIBAL QUESTS (REDEEMED MOUNT OR MINION) -> furry kategorien
[
    Amalj'aa    -> Scaley
    Sylphs      -> Fey
    Kobolds     -> Furry
    Sahagin     -> Auquarian
    Ixali       -> Avian
    Vanu Vanu   -> Avian
    Vath        -> Scaley
    Moogles     -> Fey
    Kojin       -> Scaley
    Ananta      -> Scaley
    Namazu      -> Auquarian
    Pixies      -> Fey
    Dwarves     -> Fey
    Qitari      -> Furry
    Arkasodara  -> Pachyderm
    Loporrits   -> Furry
    Omicrons    -> Synth
]

RACE AND GENDER DISTRIBUTION -> which gender plays longer & maybe per furry race

HOW MANY CHARACTERS ARE THERE? -> player counter per geolocation


https://activeplayer.io/final-fantasy-xiv/#
https://www.rand.org/nsrd/projects/terrorism-incidents.htmlurryscaley

Player Count -> Player Count on Historical Days (911)

