== Data
=== Sources
==== FFXIVCensus
Data from https://ffxivcensus.com was used for the following raw .csv:

* American_Realms.csv -> https://ffxivcensus.com/#rat-na
* Japanese_Realms.csv -> https://ffxivcensus.com/#rat-jp
* American_Realms.csv -> https://ffxivcensus.com/#rat-eu
* Japanese_Realms.csv -> https://ffxivcensus.com/#rat-oc
* American_Realms_Endgame.csv -> https://ffxivcensus.com/#ra-na
* Japanese_Realms_Endgame.csv -> https://ffxivcensus.com/#ra-jp
* American_Realms_Endgame.csv -> https://ffxivcensus.com/#ra-eu
* Japanese_Realms_Endgame.csv -> https://ffxivcensus.com/#ra-oc
* GrandCompanies.csv -> https://ffxivcensus.com/#grandcompany (All Characters)
* Species_Sex.csv -> https://ffxivcensus.com/#racegender (All Characters)
* Species_Sex_Endgame.csv -> https://ffxivcensus.com/#racegender (Endgame Characters)
* Tribal_Interactions.csv -> https://ffxivcensus.com/#tribal

Furthermore the values for Total Population and Endgame Characters was taken from: https://ffxivcensus.com/#population

=== Transformations
==== Dimensions
===== Dim_isEndgame
* 'Dim_isEngame' is a boolean value

===== Dim_GrandCompany
* 'Dim_GrandCompany' consists of 3 Grand Companies and the lack of one.

===== Dim_Realms
* 'Dim_Realms' concatenates all the 'Category' of American_Realms, European_Realms, Japanese_Realms and Oceanian_Realms.
* 'Category' is renamed to 'Dim_Realms'

===== Sub_Regions
* 'Dim_Realms' concatenates all the 'Category' of American_Realms, European_Realms, Japanese_Realms and Oceanian_Realms.
* 'Category' is renamed to 'Dim_Realms'
* Adds 'V_Region' which contains their Server Locations / Intended Regions.

==== Enrichment Dimensions

===== Dim_Species
* Copies 'Category' from Species_Sex_Engame.csv. The Endgame version is used since it is cleaner.
* 'Category' is renamed to 'Dim_Species'.

===== Sub_Sex
* 'Sub_Sex' consists of 2 sexes: male and female.

===== Dim_Tribes
* Copies 'Category' from Tribal_Interactions.csv.
* 'Category' is renamed to 'Dim_Tribes'.
* 'Tribe' is renamed to 'V_Interactions'.

===== Sub_Tribe_Categories
* 'Dim_Tribes' is copied from Dim_Tribes.
* Every Dim_Tribe gets a furry subcategory assigned, which was evaluated by professional furries. Said categories are in the column 'V_Category'.

==== Fact Tables
===== Fact
The base fact table shows the player amount per realm, grand company, and endgame status.

Steps taken to achieve this table:

* Realm-population numbers for total and endgame players as a calculation base
* Multiply by the percentile distribution of grand companies, which is calculated with the grand company population amount and the total population amount.

===== Enriched Fact
The base fact table shows the player amount per realm, grand company, endgame status, and species.

Steps taken to achieve this table:

* Realm-population numbers for total and endgame players as a calculation base
* Multiply by the percentile distribution of grand companies, which is calculated with the grand company population amount and the total population amount.
* Multiply by the percentile distribution of species, which was calculated with the total species population and the total population, or in the case of endgame characters, with the endgame species population and the endgame population.

===== Ridiculous Fact
The base fact table shows the player amount per realm, grand company, endgame status, and species. Furthermore, it also shows how many people have completed the Tribe-Interactions-Quests for the same attributes.

Steps taken to achieve this table:

* Realm-population numbers for total and endgame players as a calculation base
* Multiply by the percentile distribution of grand companies, which is calculated with the grand company population amount and the total population amount.
* Multiply by the percentile distribution of species, which was calculated with the total species population and the total population or, in the case of endgame characters, with the endgame species population and the endgame population.
* Multiply by the percentile distribution of completed quests, which was calculated with the total players who completed said quests per tribe and the total population.